language: python
python:
- '2.7'
- '3.3'
- pypy
env:
  global:
    secure: JMAKDIOGT7PxCCNDwnlAlXctgUbU+kX1Stpo+t/MTc+C2I9uZCtKWAwwFR3LWdEC0rLt6+BA50Tj5fxikFBEhKNl08MaWprFDPVziy53x+aSKtDRj7bwYO2FbvrRPdol8EJMmRzESa7EqHNGegTICkgxNkLm6BVF/avht4u1gXhtOZuAbPXTnwjoe3ukQxwjTLgRTdTdOUdrcudMIQUCZzyEzpsIu3GvZd9oAr0WHyM6d/GQRobzb5Pmjz3b0IWLVPuJGRZIazkxeTJg9LEtj4WF7JsGKauNaF55Gx5ef5kDMZmu97Prg3XnxLUWtdyRpdMJv7E4XF/ARpWFSgdRzAmXXYgqr5em68d5GJnTndCMo98AiRCsC97po88MWNN/71KS5cVhK4LEReHx7RwENjcaiKPyQDDTtXHHqdt2rT5qfHrcAVzb3xEFkYVHmg7ZgQdk1TMF2WVQi7O/JOO/9mRS0j6xXnI6YbOdmFTN7RMIAOspa11+x3q0YLuGcaA8CddlIlrvkSblzNflz/pDk0rLz8+mLBvGg5nYShPKXVDUENdijIF9pY7caucdGeywTzXZ+E2moGNopSeAFY6tYzkWzLuaql8+c1Fq1rU4IvYpAdING8k8PeYrC4t4PYIcVXKPSJ5vOMHfB2hsD08y/QLxjUql3WZJhzgdjsuGLsk=

install: 
    - pip install -e .
    - pip install flake8 yapf

script: 
   - 
